# Generated by Django 4.2.5 on 2023-11-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('art_type', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('out-of-stock', 'Out of Stock')], max_length=20)),
                ('product_image', models.ImageField(max_length=255, upload_to='product_images/')),
            ],
        ),
    ]
