# Generated by Django 4.2.5 on 2023-11-13 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='am_pm',
        ),
    ]
