# Generated by Django 4.2.5 on 2023-11-13 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_competition_am_pm'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='am_pm',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
