# Generated by Django 4.2.5 on 2023-11-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
