# Generated by Django 4.2.5 on 2024-02-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
