# Generated by Django 4.2.5 on 2024-02-17 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('about_product', models.TextField()),
                ('auction_start_datetime', models.DateTimeField()),
                ('auction_end_datetime', models.DateTimeField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.ImageField(max_length=255, upload_to='auction_product_images/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
