# Generated by Django 4.2.5 on 2024-02-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_bid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
